server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:~/todoDB
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    use_sql_comments: true
    format_sql: true
    ddl-auto: update
  h2:
    console:
      enabled: true
    path: /h2-console